apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: message-queue-provider
spec:
  package: deploy-releases-hyperspace-docker.common.cdn.repositories.cloud.sap/crossplane/provider-message-queue:1.0.0-20230109084715
  packagePullSecrets:
   - name: artifactory-readers